package com.kevin.rfidmanager.database;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;
import org.greenrobot.greendao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "KEY_DESCRIPTION".
*/
public class KeyDescriptionDao extends AbstractDao<KeyDescription, Long> {

    public static final String TABLENAME = "KEY_DESCRIPTION";

    /**
     * Properties of entity KeyDescription.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Rfid = new Property(1, String.class, "rfid", false, "RFID");
        public final static Property KeyDescription = new Property(2, String.class, "keyDescription", false, "KEY_DESCRIPTION");
    }


    public KeyDescriptionDao(DaoConfig config) {
        super(config);
    }
    
    public KeyDescriptionDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"KEY_DESCRIPTION\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT UNIQUE ," + // 0: id
                "\"RFID\" TEXT," + // 1: rfid
                "\"KEY_DESCRIPTION\" TEXT);"); // 2: keyDescription
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"KEY_DESCRIPTION\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, KeyDescription entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String rfid = entity.getRfid();
        if (rfid != null) {
            stmt.bindString(2, rfid);
        }
 
        String keyDescription = entity.getKeyDescription();
        if (keyDescription != null) {
            stmt.bindString(3, keyDescription);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, KeyDescription entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String rfid = entity.getRfid();
        if (rfid != null) {
            stmt.bindString(2, rfid);
        }
 
        String keyDescription = entity.getKeyDescription();
        if (keyDescription != null) {
            stmt.bindString(3, keyDescription);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public KeyDescription readEntity(Cursor cursor, int offset) {
        KeyDescription entity = new KeyDescription( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // rfid
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2) // keyDescription
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, KeyDescription entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setRfid(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setKeyDescription(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(KeyDescription entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(KeyDescription entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(KeyDescription entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
